<!--https://get.foundation/templates-previews-sites-f6-xy-grid/ecommerce.html-->
    <div class="text-center">
          <h2>Our Newest Categories</h2>
          <hr>
    </div>
    <div class="grid-x grid-margin-x small-up-2 medium-up-2 large-up-4">
    <?php foreach($categories as $category): ?>
        <div class="cell">
          <img class="thumbnail" src="https://placehold.it/500x600">
          <h5><?= $category['name'] ?></h5>
          <p><?= $category['description'] ?></p>
          <a href="" class="button expanded">Buy</a>
        </div>
    <?php endforeach; ?>
    </div>