<h1>Créer une nouvelle catégorie</h1>
<form action="index.php?route=create-category" method="POST">
    <fieldset>
        <label for="name">Nom :</label>
        <input type="text" name="name" id="name"/>
    </fieldset>
    <fieldset>
        <label for="description">Description :</label>
        <input type="text" name="description" id="description"/>
    </fieldset>
    <input type="submit" value="Valider" name="submit-new-category" id="submit-new-category"/>
</form>