<form action="index.php?route=edit-user" method="POST">
    <legend>Modifier votre compte</legend>
    <fieldset>
        <label for="firstName"> Nom  : </label>
        <input type="text" id="firstName" name="firstName">
    </fieldset>
    <fieldset>
        <label for="lastName"> Prénom : </label>
        <input type="text" id="lastName" name="lastName">
    </fieldset>
     <fieldset>
        <label for="email"> Email : </label>
        <input type="email" id="email" name="email">
    </fieldset>
     <fieldset>
        <label for="password"> Mot de passe : </label>
        <input type="password" id="password" name="password">
    </fieldset>
        <input type="submit" value="Modifier" name="submit-edit-user" id="submit-edit-user">
</form>