<h1>Se connecter</h1>
<form action="index.php?route=login" method="POST">
    <fieldset>
        <label for="email">Email :</label>
        <input type="email" name="email" id="email"/>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password"/>
    </fieldset>
    <input type="submit" name="submit-login" id="submit-login" value="Connexion"/>
</form>